permalink: /:year/:month/:day/:title
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    hard_wrap: false
plugins:
  - jekyll-feed
  - jekyll-sitemap
name:         Raghav Sood
description:  It's a blog
url:          https://raghavsood.com
author:
  twitter: ARaghavSood
timezone: Pacific/Auckland
permalink: pretty
